apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
      argocd-image-updater.argoproj.io/image-list: demo=192.168.1.18:5001/demo:*
      argocd-image-updater.argoproj.io/demo.update-strategy: latest
      argocd-image-updater.argoproj.io/update-interval: 1m
spec:
  project: default

  source:
    repoURL: https://github.com/ntripur00/sampleAPIInfra.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true