apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: ghcr.io/ntripur00/demo:20230414-212906
#          repository: http://192.168.1.18:5001/demo
          imagePullPolicy: Always
#          insecureSkipVerify: true
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: my-registry-cred
          insecureSkipVerify: true
          host: 192.168.1.18:5001
          repository: "http://192.168.1.18:5001/demo"
      env:
        - name: REGISTRY_INSECURE
          value: "true"