apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: http://192.168.1.18:5001/demo:20230414-150413
#          repository: 192.168.1.18:5001/demo
          imagePullPolicy: Always
#          insecureSkipVerify: true
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: my-registry-credential
          insecureSkipVerify: true
      env:
        - name: REGISTRY_INSECURE
          value: "true"