apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: test

commonLabels:
  app: demo
configMapGenerator:
- name: demo-config
  files:
  - argocd-image-updater-configmap.yaml